- name: Deploy services to remote.
  hosts: deploy
  tasks:
    - name: Copy dependencies package to remote
      become: true
      copy:
        src: "{{ dependencies_path_local }}"
        dest: "{{ dependencies_path_destination }}"

    - name: Copy docker package to remote
      become: true
      copy:
        src: "{{ docker_path_local }}"
        dest: "{{ docker_path_destination }}"
        
    - name: Copy docker image to remote
      become: true
      copy:
        src: "{{ docker_image_path }}"
        dest: "{{ docker_image_path_destination }}"

    - name: Copy docker-compose package to remote
      become: true
      copy:
        src: "{{ docker_compose_path_local }}"
        dest: "{{ docker_compose_path_destination }}"
        mode: 'u+x,g+x'

    - name: Copy docker-compose yaml to remote
      become: true
      template:
        src: "./docker-compose.yml.j2"
        dest: "{{ remote_project_path }}docker-compose.yml"

    - name: Copy project config and dockefile
      become: true
      copy:
        src: "{{ item }}"
        dest: "{{ remote_project_path }}"
        mode: 'u=rwX,g=rX,o=rX'
      with_items:
        - ./dockerfile
        - ./conf

    - name: Finding dependencies files
      find:
        paths: "{{ dependencies_path_destination }}"
        patterns: "*.rpm"
      register: dependencies_result

    - name: Install dependencies
      become: true
      yum:
        name: "{{ item.path }}"
        state: present
      with_items: "{{ dependencies_result.files }}"

    - name: Finding docker package
      find:
        paths: "{{ docker_path_destination }}"
        patterns: "*.rpm"
      register: docker_result

    - name: Install docker
      become: true
      yum:
        name: "{{ item.path }}"
        state: present
      with_items: "{{ docker_result.files }}"

# rpm -ivh package.rpm