- name: "Export docker image"
  hosts: localhost
  tasks: 
   - name: "export keepalive"
     shell: "docker save -o {{ docker_image_path }}keepalived_{{ keepalive_version }}.tar osixia/keepalived:{{ keepalive_version }}"
   - name: "export elk"
     shell: "docker save -o {{ docker_image_path }}elk_{{ elk_version }}.tar docker.elastic.co/elasticsearch/elasticsearch-oss:{{ elk_version }}"
   - name: "export nginx"
     shell: "docker save -o {{ docker_image_path }}nginx_{{ nginx_version }}.tar nginx:{{ nginx_version }}"
   - name: "export logstash"
     shell: "docker save -o {{ docker_image_path }}logstash_{{ logstash_version }}.tar ansiblemars_logstash:{{ logstash_version }}"